Octree with triangles getting stack overflown the point insertion.
I am getting the exception StackOverflow, I tryied to catch the exception but now I am getting the error C2712 cannot use __try in functions that require object unwinding.